self.addEventListener('install',e=>{
  e.waitUntil(caches.open('study-cache-v1').then(c=>c.addAll([
    './','./index.html','./placement.html','./manifest.webmanifest',
    './assets/icon-192.png','./assets/icon-512.png'
  ])));
});
self.addEventListener('fetch',e=>{
  e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)));
});